"""add card.front_pronunciation

Revision ID: 0007
Revises: 0006
Create Date: 2026-05-18

IPA pronunciation of the card front, generated by OpenAI. Nullable —
existing rows stay NULL until the backfill script
(scripts/backfill_pronunciation.py) reaches them; new cards get it
populated at creation time.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0007"
down_revision = "0006"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "card",
        sa.Column("front_pronunciation", sa.Text(), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("card", "front_pronunciation")
